# Generated by Django 3.1 on 2020-08-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbasenutrition',
            name='client_nutrition_preference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fitness.clientnutritionpreference'),
        ),
    ]
