# Generated by Django 3.1 on 2020-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0002_auto_20200823_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnutritionpreference',
            name='extra_calories',
            field=models.IntegerField(db_column='extra_calories', verbose_name='Calories Extra'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='nom_repas',
            field=models.TextField(db_column='repas', verbose_name='Repas'),
        ),
    ]
