# Generated by Django 3.1 on 2020-08-30 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0003_auto_20200825_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='num_repas',
            field=models.PositiveSmallIntegerField(blank=True, db_column='num_repas', null=True, verbose_name='Numéro de repas'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fitness.client'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_day',
            field=models.PositiveSmallIntegerField(blank=True, db_column='train_day', null=True, verbose_name="Journée d'entraînement"),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='training_type',
            field=models.CharField(blank=True, db_column='type_train', max_length=255, null=True, verbose_name="Type d'entraînement"),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='nom_repas',
            field=models.TextField(blank=True, db_column='repas', null=True, verbose_name='Repas'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='qte_calories',
            field=models.FloatField(blank=True, db_column='Calories', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='qte_carbs',
            field=models.FloatField(blank=True, db_column='Carbs', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbs'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='qte_fat',
            field=models.FloatField(blank=True, db_column='Fat', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='qte_protein',
            field=models.FloatField(blank=True, db_column='Protein', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Proteins'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='nom_exercice',
            field=models.CharField(blank=True, db_column='exercice', max_length=50, null=True, verbose_name="Nom d'Exercice"),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='nombre_reps',
            field=models.PositiveSmallIntegerField(blank=True, db_column='reps', null=True, verbose_name='Nombre de Reps'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='nombre_sets',
            field=models.PositiveSmallIntegerField(blank=True, db_column='sets', null=True, verbose_name='Nombre des Sets'),
        ),
    ]
