# Generated by Django 3.1 on 2020-08-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0004_auto_20200830_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fitness.client'),
        ),
    ]
