# Generated by Django 3.1 on 2020-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0006_clienttrainingdayprogram_trainingexercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingexercise',
            options={'verbose_name': "Exercice d'entraînement", 'verbose_name_plural': "Exercices d'entraînements"},
        ),
        migrations.AlterField(
            model_name='clienttrainingdayprogram',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, to='Fitness.TrainingExercise'),
        ),
    ]
