# Generated by Django 3.1 on 2020-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness', '0008_auto_20201026_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='nombre_reps',
            field=models.CharField(blank=True, db_column='reps', max_length=50, null=True, verbose_name='Nombre de Reps'),
        ),
    ]
